name: C++ testing matrix
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [gcc, clang]
    steps:
     - uses: actions/checkout@v2
     - run: echo ${{matrix.compiler}}
     - name: setup build directory
       run: mkdir $HOME/build && cd $HOME/build
     - name: configure
       run: cmake $GITHUB_WORKSPACE -DCMAKE_CXX_COMPILER=${{ matrix.compiler }}
     - name: make
       run: make
     - name: ctest
       run: ctest
