name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: setup build directory
      run: mkdir $HOME/build && cd $HOME/build
    - name: configure
      run: cmake $GITHUB_WORKSPACE
    - name: make
      run: make
    - name: ctest
      run: ctest
