name: comment_on_pr

# read-write repo token
# access to secrets
on:
  workflow_run:
    workflows: ["pr_comment_trigger"]
    types:
      - completed

jobs:
  upload:
    permissions:
      actions: read
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    if: github.event.workflow_run.event == 'issue_comment'
    steps:
      - name: echo
        shell: bash
        run: echo "github.workspace ${{github.workspace}}"
